name: quizgenie
services:
  postgres:
    image: postgres:15
    restart: ${PG_RESTART_POLICY:-always}
    environment:
      POSTGRES_USER: ${DB_USER:-quizgenie}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-quizgenie}
      POSTGRES_DB: ${DB_NAME:-quizgenie}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${PG_HOST_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-quizgenie}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
